import { FaReact } from "react-icons/fa";
import {
  SiBootstrap,
  SiMui,
  SiNextdotjs,
  SiReactquery,
  SiRecoil,
  SiRedux,
  SiTailwindcss,
  SiTypescript,
  SiNestjs,
  SiShadcnui,
  SiSocketdotio,
  SiExpress,
  SiNodedotjs,
  SiPostgresql,
  SiPhp,
  SiMysql,
} from "react-icons/si";

export const iconMap: Record<string, JSX.Element> = {
  FaReact: <FaReact size={25} className="text-sky-600" />,
  SiBootstrap: <SiBootstrap size={25} className="text-indigo-500 " />,
  SiMui: <SiMui size={25} className="text-blue-300" />,
  SiNextdotjs: <SiNextdotjs size={25} />,
  SiReactquery: <SiReactquery size={25} className="text-rose-500" />,
  SiRecoil: <SiRecoil size={25} className="text-blue-600" />,
  SiRedux: <SiRedux size={25} className="text-purple-600" />,
  SiTailwindcss: <SiTailwindcss size={25} className="text-cyan-300" />,
  SiTypescript: <SiTypescript size={23} className="text-blue-400" />,
  SiNestjs: <SiNestjs size={25} className="text-rose-600" />,
  SiShadcnui: <SiShadcnui size={23} className="text-white" />,
  SiSocketdotio: <SiSocketdotio size={25} className="text-white" />,
  SiExpress: <SiExpress size={25} className="text-white" />,
  SiNodedotjs: <SiNodedotjs size={25} className="text-green-700" />,
  SiPostgresql: <SiPostgresql size={25} className="text-blue-300" />,
  SiPhp: <SiPhp size={25} className="text-sky-600" />,
  SiMysql: <SiMysql size={25} className="text-orange-500" />,
};
